---
- name: Configure Docker
  hosts: [server]
  become: true
  tasks:
  - name: apt updating
    command: sudo apt update
  - name: Install python and Pip
    command: sudo apt install -y python-pip
  - name: Install Docker
    command: sudo apt-get install -y docker.io
    become: yes
    become_user: root
  - name: start docker
    command: sudo systemctl start docker
    become: yes
    become_user: root
  - name: Deploy the image from Dockerhub and run as container
    command: docker run -itd -p 8080:8081 mmidlaj/insureme_project:latest
